name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: debug
      run: ls
      
    - name: make
      run: make -f makefile common PLATFORM="rg35xx rg35xxplus"
    - name: make all
      run: make -f makefile all

